spring.datasource:
    url: jdbc:mysql://localhost:3306/appliers
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

server.port: 8080

swagger.enabled: true
springfox.documentation.swagger.v2.path: /demo/swagger/v2/api-docs

spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
        matching-strategy: ant_path_matcher